[build]
builder = "NIXPACKS"

[build.nixpacksConfig.aptPkgs]
pkgs = ["tesseract-ocr", "tesseract-ocr-vie", "poppler-utils", "libgl1"]

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn eduflow.wsgi --bind 0.0.0.0:$PORT --timeout 300 --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
