# Generated by Django 6.0.2 on 2026-02-26 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("Theory", "Lý thuyết"),
                    ("Slide", "Slide bài giảng"),
                    ("Textbook", "Giáo trình"),
                    ("Examples", "Ví dụ minh họa"),
                    ("Exercises", "Bài tập"),
                    ("PastExam", "Đề thi các năm"),
                    ("Other", "Khác"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions_json", models.TextField()),
                ("answers_json", models.TextField(default="[]")),
                ("score", models.FloatField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("is_submitted", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to="study.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
