# Generated by Django 6.0.2 on 2026-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_add_uploaded_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="retrieved_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
